### PR TITLE
Duct Tape Solution Fall Damage

### PR DESCRIPTION
**Pull request by Dream-Master**

### CODE REVIEW

**Comment by Dream-Master** [comment]
@fewizz Not sure what make conflicts here.

**Comment by fewizz** [comment]
No, sorry, that's bad solution =P. I am working on this rn.

**Comment by Dream-Master** [comment]
OK. Sorry i dont have so much Java knowledge.

**Comment by fewizz** [comment]
MC is increasing fallDistance when player falling, but not decreasing when player rise(fly up), is means that if player will fly up and down many times, fallDistance will be too big, as a damage =P

**Comment by Dream-Master** [comment]
ok is it easy to add ?

**Comment by fewizz** [comment]
[Can you test it?](https://drive.google.com/file/d/0BwY_2FEZWt8dZEVhOVA2TW1DaDg/view?usp=sharing) . If everything is ok, will upload to curse. Thanks :3

**Comment by Dream-Master** [comment]
Ok will do give a few mins.

**Comment by Dream-Master** [comment]
OK Feather wings 2,5 heats
Thaumium 5 heats
Nano 8 hearth
Quantum get damage but less then half heart.

Works so far. I only jump from a tower. With nothing weared i died.

**Comment by fewizz** [comment]
thanks again.

**Pull request closed without merging**
